OnlineShop/OnlineShop/ViewModels/User/UserListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.ViewModels.User
{
    public class UserListViewModel
    {
        public List<UserViewModel> users = new List<UserViewModel>();
    }
}

OnlineShop/OnlineShop/ViewModels/User/UserOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.ViewModels.User
{
    public class UserOrder
    {
        public int OrderId { get; set; }
        
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime OrderDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public long Total { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }

    }
}

OnlineShop/OnlineShop/ViewModels/User/UserOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.ViewModels.User
{
    public class UserOrderViewModel
    {
        public int OrderId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public DateTime OrderDate { get; set; }
        public string Address { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public long Total { get; set; }
     }
}

OnlineShop/OnlineShop/ViewModels/User/UserViewModel.cs
using Online_Shop.Application.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.ViewModels.User
{
    public class UserViewModel
    {

        public string FName { get; set; }
        public string LName { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public DateTime DOB { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string SecQuest { get; set; }
        public string ImgUrl { get; set; }
        public string Answer { get; set; }
        public int roleId { get; set; }
       
    }
}

OnlineShop/OnlineShop/Controllers/CheckOutController.cs
using Online_Shop.Application.Business_Layer;
using Online_Shop.Application.DataAccessLayer;
using Online_Shop.Application.Entities;
using OnlineShop.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    [Authorize]
    public class CheckOutController : Controller
    {
        ShopDAL Data = new ShopDAL();
        BusinessLayer bl = new BusinessLayer();
        const string PromoCode = "Free";
        //
        // GET: /CheckOut/

        public ActionResult AddressAndpayment()
        {
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            if (cart.GetCount() == 0)
            {
                return View("EmptyCart"); //View("Please add at least 1 Product in Cart....");
            }
            return View();
        }

        [HttpPost]
        [UserFilter]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            Order Order = new Order();
            TryUpdateModel(Order);
            //try
            //{
            //if (string.Equals(values["PromoCode"], PromoCode, StringComparison.OrdinalIgnoreCase))
            if (values["PromoCode"] == PromoCode)
            {
                return View(Order);
            }
            else
            {
                Order.UserName = User.Identity.Name;
                Order.OrderDate = DateTime.Now;
                Data.Order.Add(Order);
                Data.SaveChanges();
                ShoppingCart_BusinessLayer cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
                Notifications n = new Notifications()
                {

                    category = "Order",
                    Description = Order.UserName + "placed a new Order. PLEASE REVIEW",
                    time = DateTime.Now
                };
                bl.PostNotification(n);
                cart.CreatOrder(Order);
                return RedirectToAction("Complete", new { id = Order.OrderId });
            }
        }
        //    //catch
        //    //{
        //    //    return View(Order);
        //    //}
        //}

        public ActionResult Complete(int id)
        {
            bool isValid = Data.Order.Any(o => o.OrderId == id && o.UserName == User.Identity.Name);
            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }


    }
}

OnlineShop/OnlineShop/Controllers/ShoppingCartController.cs
using Online_Shop.Application.DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using OnlineShop.Models;
using System.Web;
using System.Web.Mvc;
using Online_Shop.Application.Business_Layer;
using OnlineShop.Models.ShopingCart;
using Online_Shop.Application.Entities;
using OnlineShop.ViewModels;

namespace OnlineShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        ShopDAL Data = new ShopDAL();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);

            ShoppingCartViewModel ViewModel = new ShoppingCartViewModel()
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            foreach (Cart itm in ViewModel.CartItems)
            {
                itm.product = Data.Products.Single(c => c.Id == itm.ProductId);
            }

            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult AddtoCartDt(string id,string quantity)
        {
            int id2 = int.Parse(id);
            Product pro = Data.Products.Single(c => c.Id == id2);
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            int l = int.Parse(quantity);
            for (int i = 0; i < l; i++)
            {
                cart.AddToCart(pro);
            }
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary", summ);

            //return RedirectToAction("CartSummary1", "ShoppingCart");
            //return RedirectToAction("Index","Product");
        }

        public ActionResult AddtoCart(int id)
        {
            
            Product pro = Data.Products.Single(c => c.Id == id);
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cart.AddToCart(pro);
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary", summ);

            //return RedirectToAction("CartSummary1", "ShoppingCart");
            //return RedirectToAction("Index","Product");
        }

       

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            Cart cart1 = Data.Cart.Single(c => c.RecordId == id);
            string product = Data.Products.Single(c => c.Id == cart1.ProductId).Description;
            //.product.Description;
            cart.removeFromCart(id);
            ShopingCartRemoveModel Result = new ShopingCartRemoveModel()
            {
                Message = Server.HtmlEncode(product) + "has been removed from the cart.",
                CartTotal = cart.GetTotal(),
                CartCount= cart.GetCount1(id),//cart.GetProCount(id,cart.ShoppingCartId),  //cart.GetCount(),
                DeleteId = id
            };

            return Json(Result, JsonRequestBehavior.AllowGet);
           // return  cart1.product.Description + " is removed from the cart";
        }

        

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary",summ);
        }
	}
}

OnlineShop/OnlineShop/Controllers/UsersController.cs
using Online_Shop.Application.DataAccessLayer;
using Online_Shop.Application.Business_Layer;
using Online_Shop.Application.Entities;
using OnlineShop.Filters;
//using OnlineShop.Models;
//using OnlineShop.Models.User;
using OnlineShop.Models.UserManagment;
using OnlineShop.ViewModels.User;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace OnlineShop.Controllers
{
   // [UserFilter]
    public class UsersController : Controller
    {
        BusinessLayer bl = new BusinessLayer();
        
        //
        // GET: /Users/
        public ActionResult Index()
        {
            return View();
        }
       
        [AllowAnonymous]
        public ActionResult Register()
        {
            string chk = Convert.ToString(Session["User"]);
            if (chk != "")
            {
                return RedirectToAction("Index", "Product");
            }
            return View("Register");
        }
        //[Authorize]
         [AllowAnonymous]
        [HttpPost]
        public ActionResult RegisterUser(UserDetail ud)
        {
            int counter = 0;
            if (ModelState.IsValid)
            {
                if (bl.CheckUser(ud))
                {

                    ModelState.AddModelError("UserId", "Username is used by another user");
                }
                else
                {
                    foreach (string fn in Request.Files)
                    {
                        HttpPostedFileBase postedFile = Request.Files[fn];
                        if (Request.Files[fn] != null)
                        {
                            if (postedFile != null && postedFile.ContentLength != 0)
                            {
                                string fName = DateTime.Now.Ticks + "_" + ++counter + postedFile.FileName.Substring(postedFile.FileName.LastIndexOf("."));
                                string WebUrl = "~/images/UserImg/" + fName;
                                string physicalPath = Request.MapPath(WebUrl);
                                postedFile.SaveAs(physicalPath);
                                ud.imgUrl = WebUrl;
                            }
                        }
                    }
                    if (ud.imgUrl == null)
                    {
                        ModelState.AddModelError("imgUrl", "Please Upload your Image");
                    }
                    //bl.SendMail(ud.Email);
                    bl.AddUser(ud);
                    Notifications n = new Notifications()
                    {

                        category = "User",
                        Description = ud.UserId + " is registered account as a member",
                        time = DateTime.Now
                    };
                    bl.PostNotification(n);
                    return RedirectToAction("Login", "Authentication");
                }
                return View("Register",ud);
            }
            else
            {
                return View("Register",ud);
            }

        }

      
        [UserFilter]
        public ActionResult UserOrders(int id)
        {
            List<Order> orders = bl.GetOneOrder(id);
            List<UserOrderViewModel> usrO = new List<UserOrderViewModel>();
           
            foreach (Order ord in orders)
            {

                UserOrderViewModel usrV = new UserOrderViewModel(){
                OrderId=ord.OrderId,
                UserName=ord.UserName,
                Name=ord.FirstName+" "+ord.LastName,
                Address=ord.Address +" "+ ord.City + " " +ord.Country,
                Email=ord.Email,
                OrderDate=ord.OrderDate,
                Phone=ord.Phone,
                Total=ord.Total
                };
                
                usrO.Add(usrV);
 
            }
            return View(usrO);

        }



        
        [AdminFilters]
        public ActionResult AllUsers()
        {
            
            List<UserDetail> users= bl.GetAllUsers();
            return View("AllUsers",users);
        }
        [HttpGet]
        [UserFilter]
        public ActionResult Edit(int? id)
        {
            UserDetail usr=bl.GetUser(id);
            return View("EditUser",usr);
        }

        [HttpPost]
        [UserFilter]
        public ActionResult EditUser(UserDetail u)
        {
            if (ModelState.IsValid)
            {
                bl.EditUser(u);
                return RedirectToAction("UserAccount", "Authentication", bl.GetUser(u.Id));
            }
            else
            {
                return RedirectToAction("Edit", "Users",u);
            }
        }

        [UserFilter]
        public ActionResult DeleteAccount(int id)
        {
            bl.DeleteAccount(id);
            FormsAuthentication.SignOut();
            Session.Clear();
            return RedirectToAction("Login", "Authentication");
         }
	}
}

OnlineShop/OnlineShop/Views/Shared/LoginMessage.cshtml
<div>
    @Html.ActionLink("LOGIN -or- REGISTER", "Login", "Authentication", null, new { style = "font-size: 12px;color:white;" })
</div>

OnlineShop/OnlineShop/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>

    

    @section Scripts{
    <link href="contents/Content/bootstrap.css" rel="stylesheet" />
    <script src="contents/Scripts/bootstrap.js"></script>
    <script src="~/Contentts/Scripts/jquery-2.1.4.min.js"></script>
        }
</head>
<body>
    <div class="container" style="margin-bottom: 8px;">
        <div class="row" style="padding:0px; margin-top:8px;margin-bottom:10px;">
            <div class="col-lg-6 col-sm-6" style="float: left">
                <img src="~/images/Hs-logo-2.png" style="height: 37px; float: left;" />
                <div style="float:left;font-size:15px;margin-left:10px;">
                    <p style="color:#e8d6d6;">feel the difference</p>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div style="float: right; background-color: #f56b6b; padding: 0px; border-radius: 9px; height: auto; width: auto;">
                    <p style="color:white;float:right;font-size:18px">
                        <div style="float: right; margin: 7px;">
                            @{
                                Html.RenderAction("Name", "Authentication");
                            }
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="container" style="margin-left:-32px">
            <div class="row">
                <div style="float:left;width:40%">
                    <ul class="nav nav-pills" style="margin-left:30px;">
                        <li style="margin-left:10px;"> @Html.ActionLink("Home", "Index", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>
                        <li style="margin-left:10px;">@Html.ActionLink("Products", "AllProducts", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>
                        <li style="margin-left:10px;">@Html.ActionLink("Contact", "Contact", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>
                        
                    </ul>
                </div>
                <div style="float: left; width: 25%">
                    @{
                        Html.RenderPartial("~/Views/Product/_ProductSearch.cshtml");
    //Html.RenderAction("SearchProd1", "Product");

                    }
                </div>

                <div style="float:right;height:30px;width:33%;">

                    <div style="float: right; margin: 2px; background-color: #645a5a; padding: 5px; border-radius: 6px; ">

                        <div style="color:white;" id="summary" >
                            @{
                                Html.RenderAction("CartSummary", "ShoppingCart");
                            }
                        </div>
                    </div>
                </div>
            </div>
            @*<div>
                    @{
                        Html.RenderAction("admin", "AdminPanel");
                    }
                </div>*@
        </div>
    </div>
    <div class="container" style="margin-bottom:0px;">
        <div class="row">
            <div style="float:right">

                <ul class="nav nav-pills" style="margin-left:30px;">
                   <li>
                       @{
                           Html.RenderAction("AdminLink", "Product");
                       }
    </li>  
                    <li> @Html.ActionLink("My Account", "UserAccount", "Authentication", new {returnUrl=Request.RawUrl }, new { style = "color:#645a5a;" })</li>
                    @*<li style="margin-right: 2px;"> <img src="~/images/download.png" height="25" width="25" style="float:right" /></li>*@
                    <li>
                        <a href="@Url.Action("Index", "ShoppingCart")" title="Widget View" class="links" style="color:#645a5a;">
                            <img alt="Widget View" height="25" width="25" src="@Url.Content("~/images/download.png") " style="margin-right:3px;">
                            Shopping Cart
                        </a>
                    </li>   
                    
                    @*<li style="margin-left:2px;">    @Html.ActionLink("Shopping Cart", "Index", "ShoppingCart", null, new { style = "color:#645a5a;" })</li>*@
                    <li> @Html.ActionLink("Check Out", "AddressAndPayment", "CheckOut", null, new { style = "color:#645a5a;" })</li>
                                
                
                </ul>
            </div>
        </div>
    </div>
   
    <hr />
    <div class="container " style="margin-bottom: 20px;margin-top:10px;">
    
        @RenderBody()
    
   <hr />

        <div class="container" style="border: thin thick; margin-bottom: 20px;margin-top:20px;">

            <div class="row">
                <div class="col-lg-4">
                    <b>Twitter Updates</b>
                    <p style="margin:5px;">
                        Check out this great #themeforest item for you 'Simpler Landing' http://t.co/LbLwldb6 2 hours ago
                    </p>
                    <hr />
                </div>
                <div class="col-lg-4">
                    <b>News Letter Sign Up</b>
                    <p style="margin:5px;">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    </p>
                    <hr />
                    <div>
                        Subscribe Now:
                    </div>
                   @{
                       Html.RenderPartial("~/Views/Authentication/_Subscriber.cshtml");
                   }
                  
                </div>
                <div class="col-lg-4">
                    <b>Shopping</b>
                    
                    <p id="check">
                        +387 123 456<br /> +387 123 456
                        <br />
                        +387 123 456
                    </p><hr />
                    <p>
                        +387-123-456-1<br />
                        +387-123-456-2
                    </p><hr />
                    <p>
                        your@email.com<br />
                        customer.care@mail.com
                    </p>
                </div>
            </div>

            <hr />
        </div>
        </div>


  
</body>
</html>

OnlineShop/OnlineShop/Views/Shared/MyLayout2.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>



    @section Scripts{
        <link href="contents/Content/bootstrap.css" rel="stylesheet" />
        <script src="contents/Scripts/bootstrap.js"></script>
        <script src="~/Contentts/Scripts/jquery-2.1.4.min.js"></script>
    }
</head>
<body>
    <div class="container" style="margin-bottom: 8px;">
        <div class="row" style="padding:0px; margin-top:8px;margin-bottom:10px;">
            <div class="col-lg-6 col-sm-6" style="float: left">
                <img src="~/images/Hs-logo-2.png" style="height: 37px; float: left;" />
                <div style="float:left;font-size:15px;margin-left:10px;">
                    <p style="color:#e8d6d6;">feel the difference</p>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div style="float: right; background-color: #f56b6b; padding: 0px; border-radius: 9px; height: auto; width: auto;">
                    <p style="color:white;float:right;font-size:18px">
                        <div style="float: right; margin: 7px;">
                            @{
                                Html.RenderAction("Name", "Authentication");
                            }
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="container" style="margin-left:-32px">
            <div class="row">
                <div style="float:left;width:40%">
                    <ul class="nav nav-pills" style="margin-left:30px;">
                        <li style="margin-left:10px;"> @Html.ActionLink("Home", "Index", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>
                        <li style="margin-left:10px;">@Html.ActionLink("Products", "AllProducts", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>
                        <li style="margin-left:10px;">@Html.ActionLink("Contact", "Contact", "Product", null, new { style = "color:#645a5a; font-size:15px;" })</li>

                    </ul>
                </div>
                <div style="float: left; width: 25%">
                    @{
                        Html.RenderPartial("~/Views/Product/_ProductSearch.cshtml");
    //Html.RenderAction("SearchProd1", "Product");

                    }
                </div>

               @* <div style="float:right;height:30px;width:33%;">

                    <div style="float: right; margin: 2px; background-color: #645a5a; padding: 5px; border-radius: 6px; ">

                        <div style="color:white;" id="summary">
                            @{
                                Html.RenderAction("CartSummary", "ShoppingCart");
                            }
                        </div>
                    </div>
                </div> *@
            </div>
            @*<div>
                    @{
                        Html.RenderAction("admin", "AdminPanel");
                    }
                </div>*@
        </div>
    </div>
    <div class="container" style="margin-bottom:0px;">
        <div class="row">
            <div style="float:right">

                <ul class="nav nav-pills" style="margin-left:30px;">
                    <li>
                        @{
                            Html.RenderAction("AdminLink", "Product");
                        }
                    </li>
                    <li> @Html.ActionLink("My Account", "UserAccount", "Authentication", new { returnUrl = Request.RawUrl }, new { style = "color:#645a5a;" })</li>
                    @*<li style="margin-right: 2px;"> <img src="~/images/download.png" height="25" width="25" style="float:right" /></li>*@
                    <li>
                        <a href="@Url.Action("Index", "ShoppingCart")" title="Widget View" class="links" style="color:#645a5a;">
                            <img alt="Widget View" height="25" width="25" src="@Url.Content("~/images/download.png") " style="margin-right:3px;">
                            Shopping Cart
                        </a>
                    </li>

                    @*<li style="margin-left:2px;">    @Html.ActionLink("Shopping Cart", "Index", "ShoppingCart", null, new { style = "color:#645a5a;" })</li>*@
                    <li> @Html.ActionLink("Check Out", "AddressAndPayment", "CheckOut", null, new { style = "color:#645a5a;" })</li>


                </ul>
            </div>
        </div>
    </div>

    <hr />
    <div class="container " style="margin-bottom: 20px;margin-top:10px;">

        @RenderBody()

        <hr />

        <div class="container" style="border: thin thick; margin-bottom: 20px;margin-top:20px;">

            <div class="row">
                <div class="col-lg-4">
                    <b>Twitter Updates</b>
                    <p style="margin:5px;">
                        Check out this great #themeforest item for you 'Simpler Landing' http://t.co/LbLwldb6 2 hours ago
                    </p>
                    <hr />
                </div>
                <div class="col-lg-4">
                    <b>News Letter Sign Up</b>
                    <p style="margin:5px;">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    </p>
                    <hr />
                    <div>
                        Subscribe Now:
                    </div>
                    @{
                        Html.RenderPartial("~/Views/Authentication/_Subscriber.cshtml");
                    }

                </div>
                <div class="col-lg-4">
                    <b>Shopping</b>

                    <p id="check">
                        +387 123 456<br /> +387 123 456
                        <br />
                        +387 123 456
                    </p><hr />
                    <p>
                        +387-123-456-1<br />
                        +387-123-456-2
                    </p><hr />
                    <p>
                        your@email.com<br />
                        customer.care@mail.com
                    </p>
                </div>
            </div>

            <hr />
        </div>
    </div>



</body>
</html>

OnlineShop/OnlineShop/Views/Shared/Partial1.cshtml
<div class="container-fluid">
    <div class="row" style=" background-color: #9ac43f; color: white; height: 30px; margin-left: 1px; margin-right: 1px;">
        <div class="col-lg-6">         
                <div style="margin:7px;float:left;">FREE HOME DELIVERY</div>
                <div style="margin:7px;">HOT LINE:  +92 51 5041174</div>
           
        </div>

        <div class="col-lg-6">  
            <div style="float: right; margin: 7px">
                @{
                    Html.RenderAction("Name", "Authentication");
                    }
            </div>
            </div>
    </div>
</div>
<div class="container-fluid" style="height:100px;">
    <div class="row" style="padding:18px">
        <div class="col-lg-6">
            <img src="~/images/Hs-logo-2.png" />
        </div>
        <div class="col-lg-6">
            <p style="color:#8e7636;text-align:right;font-size:18px">
                Need a Helping Hand <br />
                Karachi: +92-33-8593040 <br />
                Lahore : +92-33-8593040 <br />
            </p>
        </div>
    </div>
</div>
<div class="container-fluid" style="margin:0px;">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span> <span class="icon-bar">
                </span> <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">HOME SHOPING.pk</a>
        </div> 
        <div class="collapse navbar-collapse" id="example-navbar-collapse">
    <ul class="nav navbar-nav" style="margin-bottom:0px;">

        <li>@Html.ActionLink("HOME", "Index", "Product")</li>
        <li><a href="#">LAPTOPS</a></li>
        <li><a href="#">CONTACT</a></li>
        <li><a href="#">SUPPORT</a></li>
    </ul>
    <div style="float:right;padding:2px;border:double thin;border-radius:4px; margin-top:4px;width:170px;background-color:white;">
        <div class="col-lg-6">
            <div style="float: left; margin: 2px">
                @{
                    Html.RenderAction("CartSummary", "ShoppingCart");
                }
            </div>
        </div>
        @*<div style="float:left;" id="num"> 1</div> <div style="float:left;margin-left:10px;font-family:Verdana;"> item</div><div id="price" style="float: right; font-family: Verdana;"> 230000.00</div>*@
    </div>
</div>        
    </nav>
</div>

OnlineShop/OnlineShop/Views/Shared/Partial2.cshtml
<div >
    Admin @Html.ActionLink("LOGOUT", "LogOut", "Authentication", null, new { style = "color:Black" })
   @ViewBag.name
</div>

OnlineShop/OnlineShop/Views/Shared/User.cshtml
@using OnlineShop.Models
@model messag

<div>
 
   <div style="color:white;float:left"> @Model.username</div><div style="float:right">  @Html.ActionLink(" LOGOUT", "LogOut", "Authentication", null, new { style = "color:Black" }) </div>
   
    </div>

OnlineShop/OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Layout</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>