OnlineShop/OnlineShop/Models/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineShop.Models.Products
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage="you must enter its title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "you must enter its description")]        
        public string Description { get; set; }
        public string Color { get; set; }
        [Required(ErrorMessage = "you must enter its Processor type")]

        public string ProcessorType { get; set; }
        public string RAM { get; set; }
        public string HardDrive { get; set; }
        public string OperatingSystem { get; set; }
        public bool WebCam { get; set; }
        public string ScreenSize { get; set; }
        public string Status { get; set; }
        public string DedicatedGraphicMemory { get; set; }
        //public List<string> ImgUrls { get; set; }
        public int Price { get; set; }
    }
}

OnlineShop/OnlineShop/Models/Products/CreatProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.Models.Products
{
    public class CreatProductModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string ProcessorType { get; set; }
        public string RAM { get; set; }
        public string HardDrive { get; set; }
        public string SelectedOperatingSystem { get; set; }
        public bool SelectedWebCam { get; set; }
        public string ScreenSize { get; set; }
        public string Status { get; set; }
        public string DedicatedGraphicMemory { get; set; }
        //public List<string> ImgID { get; set; }
        public int SelectedCategoryId { get; set; }
    }
}

OnlineShop/OnlineShop/Models/Products/QuantityModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.Models.Products
{
    public class QuantityModel
    {
        public int id { get; set; }

        public int quantity { get; set; }
    }
}

OnlineShop/OnlineShop/Models/Products/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.Models.Products
{
    public class ReviewViewModel
    {
        public int Id { get; set; }
        public string ReviewText { get; set; }
        public string UserId { get; set; }
        public DateTime days { get; set; }
        public string ImgUrl { get; set; }
    }
}

OnlineShop/OnlineShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.ViewModels;
using Online_Shop.Application.DataAccessLayer;
using Online_Shop.Application.Business_Layer;
using Online_Shop.Application.Entities;
using OnlineShop.Filters;
using OnlineShop.Models.Products;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        BusinessLayer bl = new BusinessLayer();

        [AllowAnonymous]
       
        public ActionResult Index()
        {
            BusinessLayer bl=new BusinessLayer();
            List<Product> products = bl.GetAllProducts();
            List<images> imagesList = bl.GetImages();
            foreach(Product item in products)
            {
                item.ImgUrls = bl.FindImgs(item.Id);
            }
            return View("Index", products);
        }

        public ActionResult AllProducts()
        {
            BusinessLayer bl = new BusinessLayer();
            List<Product> products = bl.GetAllProducts();
            List<images> imagesList = bl.GetImages();
            foreach (Product item in products)
            {
                item.ImgUrls = bl.FindImgs(item.Id);
            }
            return View("AllProducts", products);
        }

       
        [HttpGet]
        public ActionResult Categories(int? id)
        {
            
            //int? a = id;
            List<Product> products = bl.SelectByCategory(id);
            List<images> imagesList = bl.GetImages();
            foreach (Product item in products)
            {
                item.ImgUrls = bl.FindImgs(item.Id);
            }
            if (products != null)
            {
                //return View("DellCategory", products);
                return View("Categories", products);
            }
            else
                return View("Categories");
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult GetNewLink()
        {
            ProductViewModel p = new ProductViewModel();
            return PartialView("_AddNew",p);
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult SearchProd1()
        {
            return PartialView("~/Views/Product/_ProductSearch.cshtml");
        }


        [HttpPost]
        public ActionResult SearchProd(string Query)
        {
            var Prods = bl.SearchPro(Query);
            List<images> imagesList = bl.GetImages();
            foreach (Product item in Prods)
            {
                item.ImgUrls = bl.FindImgs(item.Id);
            }

            ViewBag.name = Query;
            return View("Product", Prods);
        }

        [HttpPost]
        public ActionResult PostReviews(int id,string username,string review,DateTime time,int c)
        {

            Reviews r = new Reviews()
            {
                UserId = username,
                ReviewText = review,
                time = time,
                ProdId = id
            };
            Notifications n = new Notifications()
            {

                category = "Product",
                Description = username + " posted a review on the product",
                time = DateTime.Now,
                DestinationId=id
            };
            bl.PostNotification(n);
            ReviewPostViewModel r1 = new ReviewPostViewModel()
            {
                UserId = username,
                ReviewText = review,
                time = time,
                ProdId = id,
                count=c+1
            };
            bl.PostReview(r);
            //return PartialView("~/Views/Product/_Reviews.cshtml", r);
            return Json(r1, JsonRequestBehavior.AllowGet);
            
            //return RedirectToAction("Review", "Product");

        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult GetReviews(int id)
        {
            
            List<Reviews> Reviews1 = bl.GetReviews(id);
            List<ReviewViewModel> review = new List<ReviewViewModel>();
            foreach (Reviews r in Reviews1)
            {
                ReviewViewModel rm = new ReviewViewModel(){
                days = r.time,
                ReviewText = r.ReviewText,
                UserId=r.UserId
                };
                review.Add(rm);
                
            }

            ViewBag.Count = Reviews1.Count();
            return PartialView("~/Views/Product/_Reviews.cshtml",review);
        }

        
        [ChildActionOnly]
        public ActionResult AdminLink()
        {
            string chk = Convert.ToString(Session["User"]);
            if (chk == "admin")
            {
                return PartialView("AdminLink");
            }
            else
            {
                return new EmptyResult();
            }
        }
    }
}

OnlineShop/OnlineShop/Controllers/ProductsManagmentController.cs
using Online_Shop.Application.Business_Layer;
using Online_Shop.Application.DataAccessLayer;
using Online_Shop.Application.Entities;
using OnlineShop.Filters;
using OnlineShop.ViewModels.Product;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ProductsManagmentController : Controller
    {
        ShopDAL shop = new ShopDAL();
        BusinessLayer bl = new BusinessLayer();
        //
        // GET: /ProductsManagment/
        public ActionResult Index()
        {
            return View();
        }

    [AdminFilters]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
        

          ViewBag.OperatingSystem = new List<SelectListItem>
                                    {
                                        new SelectListItem{Text="Windows 10" ,Value="Windows 10" },
                                        new SelectListItem{Text="Windows 8" ,Value="Windows 8" },
                                        new SelectListItem{Text="Windows 7" ,Value="Windows 7" },
                                        new SelectListItem{Text="Windows xp" ,Value="Windows xp" }

                                    };
            ViewBag.webcam = new List<SelectListItem>
                               {
                                   new SelectListItem{Text="Yes",Value="true"},
                                   new SelectListItem{Text="No",Value="false"},
                               };
         ViewBag.Category = new List<SelectListItem>
                                {
                                    new SelectListItem{Text="DELL",Value="1"},
                                    new SelectListItem{Text="HP",Value="2"},
                                    new SelectListItem{Text="APPLE",Value="3"},
                                    new SelectListItem{Text="ACER",Value="4"},
                                    new SelectListItem{Text="LENOVO",Value="5"},
                                    new SelectListItem{Text="SAMSUNG",Value="6"},
                                    
                                    };

            //Product pro = bl.EditProduct(id);
            //return RedirectToAction("Index", "AdminPanel");    
         return View("Edit",shop.Products.Find(id));
        //return View("Index", "AdminPanel", pro);
        }

    [AdminFilters]
        [HttpPost]
        public ActionResult Edit(Product pro)
        {
            var imags = shop.Images.Where(c => c.productId == pro.Id);
            List<string> i = new List<string>();
            foreach (images img in imags)
            {
                if (img.productId == pro.Id)
                {
                    i.Add(img.ImgUrl);
                }
            }
            pro.ImgUrls = i;
            if (ModelState.IsValid)
            {
                shop.Entry(pro).State = EntityState.Modified;
                shop.SaveChanges();
                return RedirectToAction("Index", "AdminPanel");
            }
            ViewBag.OperatingSystem = new List<SelectListItem>
                                    {
                                        new SelectListItem{Text="Windows 10" ,Value="Windows 10" },
                                        new SelectListItem{Text="Windows 8" ,Value="Windows 8" },
                                        new SelectListItem{Text="Windows 7" ,Value="Windows 7" },
                                        new SelectListItem{Text="Windows xp" ,Value="Windows xp" }

                                    };
            ViewBag.webcam = new List<SelectListItem>
                               {
                                   new SelectListItem{Text="Yes",Value="true"},
                                   new SelectListItem{Text="No",Value="false"},
                               };
            ViewBag.Category = new List<SelectListItem>
                                {
                                    new SelectListItem{Text="DELL",Value="1"},
                                    new SelectListItem{Text="HP",Value="2"},
                                    new SelectListItem{Text="APPLE",Value="3"},
                                    new SelectListItem{Text="ACER",Value="4"},
                                    new SelectListItem{Text="LENOVO",Value="5"},
                                    new SelectListItem{Text="SAMSUNG",Value="6"},
                                    
                                    };
            return View(pro);
        }

    [AdminFilters]        
        public ActionResult Delete(int? Id)
        {
           
            Product pro= shop.Products.Find(Id);
            //List<images> imgs = new List<images>(); 
            bl.RemImage(Id);
            shop.Products.Remove(pro);
            shop.SaveChanges();
            return RedirectToAction("Index", "AdminPanel");

        }
       [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            Product pro= shop.Products.Find(id);
            var imags = shop.Images.Where(c => c.productId == id);
            ProductDetail product = new ProductDetail();
            
                product.Id = pro.Id;
                product.Price = pro.Price;
                product.ProcessorType = pro.ProcessorType;
                product.RAM = pro.RAM;
                product.Title = pro.Title;
                product.ImgUrls = pro.ImgUrls;
                product.Description = pro.Description;
                product.HardDrive = pro.HardDrive;
                product.WebCam = pro.WebCam;
                product.ScreenSize = pro.ScreenSize;
                product.DedicatedGraphicMemory = pro.DedicatedGraphicMemory;
                product.category = shop.Category.Single(c => c.CategoryId == pro.categoryId).Title;
                product.Status = pro.Status;
            
            List<string> i = new List<string>();
            foreach (images img in imags)
            {
                if (img.productId == pro.Id)
                {
                    i.Add(img.ImgUrl);
                }
            }
            product.ImgUrls = i;
           
            return View("Details", product);
        }

	}
}

OnlineShop/OnlineShop/Controllers/ShoppingCartController.cs
using Online_Shop.Application.DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using OnlineShop.Models;
using System.Web;
using System.Web.Mvc;
using Online_Shop.Application.Business_Layer;
using OnlineShop.Models.ShopingCart;
using Online_Shop.Application.Entities;
using OnlineShop.ViewModels;

namespace OnlineShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        ShopDAL Data = new ShopDAL();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);

            ShoppingCartViewModel ViewModel = new ShoppingCartViewModel()
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            foreach (Cart itm in ViewModel.CartItems)
            {
                itm.product = Data.Products.Single(c => c.Id == itm.ProductId);
            }

            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult AddtoCartDt(string id,string quantity)
        {
            int id2 = int.Parse(id);
            Product pro = Data.Products.Single(c => c.Id == id2);
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            int l = int.Parse(quantity);
            for (int i = 0; i < l; i++)
            {
                cart.AddToCart(pro);
            }
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary", summ);

            //return RedirectToAction("CartSummary1", "ShoppingCart");
            //return RedirectToAction("Index","Product");
        }

        public ActionResult AddtoCart(int id)
        {
            
            Product pro = Data.Products.Single(c => c.Id == id);
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cart.AddToCart(pro);
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary", summ);

            //return RedirectToAction("CartSummary1", "ShoppingCart");
            //return RedirectToAction("Index","Product");
        }

       

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            Cart cart1 = Data.Cart.Single(c => c.RecordId == id);
            string product = Data.Products.Single(c => c.Id == cart1.ProductId).Description;
            //.product.Description;
            cart.removeFromCart(id);
            ShopingCartRemoveModel Result = new ShopingCartRemoveModel()
            {
                Message = Server.HtmlEncode(product) + "has been removed from the cart.",
                CartTotal = cart.GetTotal(),
                CartCount= cart.GetCount1(id),//cart.GetProCount(id,cart.ShoppingCartId),  //cart.GetCount(),
                DeleteId = id
            };

            return Json(Result, JsonRequestBehavior.AllowGet);
           // return  cart1.product.Description + " is removed from the cart";
        }

        

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var Cart = ShoppingCart_BusinessLayer.GetCart(this.HttpContext);
            cartSummary summ = new cartSummary()
            {
                amount = Cart.GetTotal(),
                count = Cart.GetCount()
            };
            return PartialView("CartSummary",summ);
        }
	}
}

OnlineShop/OnlineShop/Views/Product/AdminLink.cshtml
    @Html.ActionLink("Admin Panel", "Index", "AdminPanel",null ,new { style = "color:#645a5a;" })

OnlineShop/OnlineShop/Views/Product/AllProducts.cshtml
@using Online_Shop.Application.Entities
@model IEnumerable<Product>
@{
    Layout = "~/Views/Shared/MyLayout.cshtml";
    ViewBag.Title = "All Products";
}
<!DOCTYPE html>

<html>
<head>
    <link href="~/Contentts/Content/bootstrap.min.css" rel="stylesheet" />

    <script src="~/Contentts/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Contentts/Scripts/bootstrap.js"></script>

    <link href="~/Contentts/CSS/Sheet.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />

    <title>Index</title>


    

</head>
<body>
<h3>All Products</h3>

    <div class="container" style=" border: thin thick; margin-bottom: 30px;">

        <div style="float:left;width:80%;">
            <div class="row" style="margin-bottom:10px;">
                @foreach (Product item in Model)
                {

                    <div class="col-lg-3 col-md-3 col-sm-6 split1" style="margin-bottom:10px;">
                        <div class="content1">
                            <div style="border-bottom: double thin; border-color: #f2e8e8; padding: 2px; height: 40%;">
                                @{
                    foreach (var i in item.ImgUrls)
                    {
                        <img src=@Url.Content(i) class="imgsize" />
                        break;
                    }
                                }
                            </div>

                            <div class="title">
                                DELL Laptop
                            </div>
                            <div class="specs">
                                @Html.ActionLink(@item.Title, "Details", "ProductsManagment", new { id = item.Id }, new { style = "color:black;" })<br />
                                @item.ProcessorType @item.RAM @item.HardDrive

                                <div style="align-items:center">@item.ScreenSize</div>
                            </div>
                            <div class="price" id=@item.Id>
                                @item.Price PKR
                            </div>
                            @*<div class="addcart btn btn-danger">

                                @*Ajax.ActionLink("AD TO CART", "AddToCart", "ShoppingCart", new { id = item.Id }, null, new AjaxOptions { OnSuccess = "handleUpdate"})*@
                            @*<button class="addcart btn btn-danger"></button>*@
                            <div id="@item.Id" class="class123">

                                @Html.ActionLink("ADD TO CART", "AddToCart", "ShoppingCart", new { id = item.Id }, new { id = item.Id, style = "color:white", @class = "addcart btn btn-danger" })
                            </div>
                            @*</div>*@
                        </div>
                    </div>


                }
            </div>
        </div>
       
    </div>
</body>
</html>

OnlineShop/OnlineShop/Views/Product/Categories.cshtml
@using Online_Shop.Application.Entities
@model IEnumerable<Product>

@{
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Category</title>

    <link href="~/Contentts/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Contentts/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Contentts/Scripts/bootstrap.js"></script>
    <link href="~/Contentts/CSS/Sheet.css" rel="stylesheet" />


</head>
<body>

    <div class="container" style="width: 980px; border: thin thick; margin-bottom: 30px;">

        <h3>Category</h3>
        <div style="float:left;width:80%;">
            <div class="row" style="margin-bottom:10px;">
                @foreach (Product item in Model)
                {
                    <div class="col-lg-4 col-md-3 col-sm-6 split1" style="margin-bottom:10px;">
                        <div class="content1">
                            <div style="border-bottom: double thin; border-color: #f2e8e8; padding: 2px; height: 40%;">
                                @{
                    foreach (var i in item.ImgUrls)
                    {
                        <img src=@Url.Content(i) class="imgsize" />
                        break;
                    }
                                }
                            </div>

                            <div class="title">
                                Laptop
                            </div>
                            <div class="specs">
                                @Html.ActionLink(@item.Title, "Details", "ProductsManagment", new { id = item.Id }, new { style = "color:black;" })<br />
                                @item.ProcessorType @item.RAM @item.HardDrive

                                <div style="align-items:center">@item.ScreenSize</div>
                            </div>
                            <div class="price" id=@item.Id>
                                RS @item.Price
                            </div>
                            @*<div class="addcart btn btn-danger">

                                @*Ajax.ActionLink("AD TO CART", "AddToCart", "ShoppingCart", new { id = item.Id }, null, new AjaxOptions { OnSuccess = "handleUpdate"})*@
                            @*<button class="addcart btn btn-danger"></button>*@
                            @Html.ActionLink("ADD TO CART", "AddToCart", "ShoppingCart", new { id = item.Id }, new { style = "color:white", @class = "addcart btn btn-danger" })

                            @*</div>*@
                        </div>
                    </div>

                }
            </div>
        </div>
        <div style="float:right;width:20%;">
            <div class="catLinks" style="border-bottom:none; padding-top: 3px; background-color:white;color:#4f4a4a;"><h4>CATEGORIES</h4></div>
            <div style="width:auto;border-right:double thin;border-bottom:double thin;border-color:#f2e8e8;">
                <ul class="nav nav-pills nav-stacked">
                    <li class="catLinks">@Html.ActionLink("DELL", "Categories", "Product", new { id = 1 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("HP", "Categories", "Product", new { id = 2 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("APPLE", "Categories", "Product", new { id = 3 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("ACER", "Categories", "Product", new { id = 4 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("LENOVO", "Categories", "Product", new { id = 5 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("SAMSUNG", "Categories", "Product", new { id = 6 }, new { style = "color:#b99a9a;" })</li>
                    <li class="catLinks">@Html.ActionLink("ASUS", "Categories", "Product", new { id = 7 }, new { style = "color:#b99a9a;" })</li>
                </ul>
            </div>
        </div>
    </div>

</body>

</html>

OnlineShop/OnlineShop/Views/Product/Contact.cshtml
@{
    Layout = "~/Views/Shared/MyLayout.cshtml";
    ViewBag.Title = "Contact";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Contacts</title>

    <link href="~/Contentts/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Contentts/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Contentts/Scripts/bootstrap.js"></script>
    <link href="~/Contentts/CSS/Sheet.css" rel="stylesheet" />
    <script src="~/Contentts/Microsoft.jQuery.Unobtrusive.Validation.2.0.30506.0/Content/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Contentts/Microsoft.jQuery.Unobtrusive.Ajax.2.0.30506.0/Content/Scripts/jquery.unobtrusive-ajax.js"></script>

</head>
<body>
    <div style="margin-bottom:200px;">
         <label>Phone:</label> <div>+387 123 456<br />
            +387-123-456-1</div>
        <label>Email:</label>customer.care.shop@gmail.com
        <div>facebook </div>
        <div>twitter</div>
    </div>
</body>
</html>

OnlineShop/OnlineShop/Views/Product/Product.cshtml
@using Online_Shop.Application.Entities
@model IEnumerable<Product>

@{
    Layout = "~/Views/Shared/MyLayout.cshtml";
    ViewBag.Title = "Product-Search";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
   <title></title>
    <link href="~/Contentts/CSS/Sheet.css" rel="stylesheet" />
    <link href="~/Contentts/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <div> 


        <div class="container" style="width: 980px; border: thin thick; margin-bottom: 60px;">

            <div style="float:left;width:80%;">
                <b> Products with Key Word " @ViewBag.name "...</b>
                <div class="row" style="margin-bottom:10px;">
                    
                        
                   @foreach(Product item in Model)
                    {

                        <div class="col-lg-4 col-md-3 col-sm-6 split1" style="margin-bottom:10px;">
                            <div class="content1">
                                <div style="border-bottom: double thin; border-color: #f2e8e8; padding: 2px; height: 40%;">
                                    @{
                        foreach (var i in item.ImgUrls)
                        {
                            <img src=@Url.Content(i) class="imgsize" />
                            break;
                        }
                                    }
                                </div>

                                <div class="title">
                                    Laptop
                                </div>
                                <div class="specs">
                                    @Html.ActionLink(@item.Title, "Details", "ProductsManagment", new { id = item.Id }, new { style = "color:black;" })<br />
                                    @item.ProcessorType @item.RAM @item.HardDrive

                                    <div style="align-items:center">@item.ScreenSize</div>
                                </div>
                                <div class="price" id=@item.Id>
                                    @item.Price PKR
                                </div>
                                @*<div class="addcart btn btn-danger">

                                @*Ajax.ActionLink("AD TO CART", "AddToCart", "ShoppingCart", new { id = item.Id }, null, new AjaxOptions { OnSuccess = "handleUpdate"})*@
                                @*<button class="addcart btn btn-danger"></button>*@
                                <div id="@item.Id" class="class123">


                                    @Ajax.ActionLink(
                                        linkText: "ADD TO CART",
                                        actionName: "AddToCart",
                                        controllerName: "ShoppingCart", routeValues: new { Id = item.Id },
                                        ajaxOptions: new AjaxOptions { HttpMethod = "post", UpdateTargetId = "summary", InsertionMode = InsertionMode.Replace, OnSuccess = "Process" }, htmlAttributes: new { style = "color:white", @class = "addcart btn btn-danger" })



                                </div>
                                @*</div>*@
                            </div>
                        </div>


                    }
                </div>
            </div>

           
        </div>


    </div>
</body>
</html>

OnlineShop/OnlineShop/Views/Product/_ProductSearch.cshtml
@*@model OnlineShop.Models.Products.SearchProductModel*@


@using (Html.BeginForm("SearchProd", "Product", FormMethod.Post, new { role = "form" }))
{
    <div  style=" float:left">
    @Html.TextBox("Query", null, new { @class = "form-control", @value="",style = "width:110%;height:30px;" ,@placeholder="enter your search..."})</div>
    <div>
        <input type="submit" value="" style="margin-left: -12px; background: url(../images/toolbar_find.png); width: 20px; height: 19px; border: 0px; margin-top: 2px; " />
    </div>

}

OnlineShop/OnlineShop/Views/Product/_Quantity.cshtml
@using OnlineShop.Models.Products
@model QuantityModel


@using (Ajax.BeginForm("Details", "ProductsManagment", new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "summary"
    }))
    {
    @Html.HiddenFor(m=>m.id)
    }